#!/bin/bash

# test reverse sort with header

set -e

output=$(mktemp)
expected=$(mktemp)

../csvsort/csvsort -c=2,1 -r << 'EOF' > $output
FirstLetter,SecondLetter
A,B
C,B
B,B
C,A
A,A
B,A
C,C
A,C
B,C
EOF

cat << 'EOF' > $expected
FirstLetter,SecondLetter
C,C
B,C
A,C
C,B
B,B
A,B
C,A
B,A
A,A
EOF

cmp $output $expected